unqualified-search-registries = ["docker.io"]

[[registry]]
prefix = "docker.io"
location = "docker.1ms.run"

[[registry]]
prefix = "docker.io"
location = "docker.apiba.cn"

[[registry]]
prefix = "docker.io"
location = "docker.cattt.net"

[[registry]]
prefix = "docker.io"
location = "docker.etcd.fun"

[[registry]]
prefix = "docker.io"
location = "docker.m.ixdev.cn"

[[registry]]
prefix = "docker.io"
location = "hub.amingg.com"

[[registry]]
prefix = "docker.io"
location = "hub.mirrorify.net"

[[registry]]
prefix = "docker.io"
location = "image.cloudlayer.icu"

[[registry]]
prefix = "docker.io"
location = "proxy.vvvv.ee"

[[registry]]
prefix = "docker.io"
location = "2a6bf1988cb6428c877f723ec7530dbc.mirror.swr.myhuaweicloud.com"

[[registry]]
prefix = "docker.io"
location = "dockerpull.pw"

[[registry]]
prefix = "docker.io"
location = "docker.kejilion.pro"

[[registry]]
prefix = "docker.io"
location = "hub1.nat.tf"

[[registry]]
prefix = "docker.io"
location = "docker-0.unsee.tech"

[[registry]]
prefix = "docker.io"
location = "docker-registry.nmqu.com"
