name: "Update Nix flake lock"

on:
  workflow_dispatch: # allows manual triggering
  schedule:
    - cron: "0 12 * * 4" # runs every Thursday at 12:00 UTC
  repository_dispatch:
    types: [update-flake-lock] # allows triggering via repository dispatch

jobs:
  nix-flake-update:
    permissions:
      contents: write
      id-token: write
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: fym998/update-flake-lock@main
